version: "3"
services:
  db:
    image: postgres:15
    container_name: bot_db
    ports:
      - "127.0.0.1:5434:5432"
    command: postgres
    volumes:
      - ./DB/data:/var/lib/postgresql/data
      - ./DB/setup:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_DB}
    healthcheck: #checks if db is operating normally, i.e. accepting connections. It is a readiness probe
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 20
  bot:
    image: movie-bot
    container_name: bot
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
